[package]
name = "wasm-array-bug"
version = "0.1.0"
authors = ["Colin Gilgenbach <colin@gilgenbach.net>"]
edition = "2018"
rust-version = "1.57"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.92"
num = "0.4.3"
num-complex = "0.4.6"
ndarray = "0.15.6"